kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://github.com/VergeDX/nixpkgs --depth=1
      - git checkout tdesktop

  - name: nix-build
    image: nixos/nix
    commands:
      - nix-build -E '(import <nixpkgs> { }).tdesktop'
