kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://github.com/VergeDX/nixpkgs tdesktop --depth=1

  - name: nix-build
    image: nixos/nix
    commands:
      - nix-build -A tdesktop
