---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: nixos/nix
    commands:
      - nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
      - nix-channel --add https://github.com/nix-community/NUR/archive/master.tar.gz nur
      - nix-channel --update
