name: "Build latest iso"
on:
  push:

jobs:
  Run-nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#iso -vL
      - uses: actions/upload-artifact@v2
        with:
          path: ./result/iso
