name: "Build minimal iso"
on: [ push ]

jobs:
  Run-nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-21.11

      - run: |
          nix-build '<nixpkgs/nixos>' \
            -A config.system.build.isoImage \
            -I nixos-config=iso.nix

      - uses: actions/upload-artifact@v2
        with:
          path: ./result/iso
